default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= Rails.application.credentials.database[:db_host] %>
  username: <%= Rails.application.credentials.database[:db_user] %>
  password: <%= Rails.application.credentials.database[:db_pass] %>

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gramolanimacion_dev
test:
  <<: *default
  database: gramolanimacion_test

production:
  <<: *default
  database: gramolanimacion_prod
  username: gramolanimacion
  password: <%= ENV["CLTEMPLATE_DATABASE_PASSWORD"] %>
